version: "3.9"

services:
  jupyter:
    image: jupyter/minimal-notebook
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./data/notebooks
        target: /home/jovyan/work

  veritas-assessment-tool:
    image: veritastool/veritas-assessment-tool
    container_name: veritas-assessment-tool
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: ./data/veritas-assessment-files
        target: /opt/veritas/file
